version: '2'

services:
    nginx:
        image: nginx
        env_file:
              - .env
        ports:
              - ${NGINX_PORT}:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/web

    php:
        build: docker/php-fpm
        env_file:
            - .env
        volumes:
            - .:/var/www:delegated
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini

    elk:
        build: docker/elk
        env_file:
            - .env
        ports:
            - ${ELK_PORT}:80
