imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels:
        - my_channel
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: notice
            channels: ['!event']
        gelf:
            type: gelf
            publisher:
                hostname: '%gelf_host%'
                port: '%gelf_port%'
            level: info
        sentry:
            type: raven
            dsn: '%sentry_dsn%'
            level: warning
        finger:
            type: fingers_crossed
            action_level: error
            handler: sentry_error
        sentry_error:
            type: raven
            dsn: '%sentry_dsn%'
            level: info
        gelf_channel_specific:
            type: gelf
            publisher:
                hostname: '%gelf_host%'
                port: '%gelf_port%'
            level: info
            channels: ['my_channel']
